on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_call:

name: Build Actions Runner

jobs:
  build-runner-image:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: generate-tag
        run: echo "tag=$(date +'%Y.%m.%d-%H%M')" >> "$GITHUB_OUTPUT"
      - uses: docker/build-push-action@v4
        with:
          context: "."
          file: "Dockerfile"
          push: true
          tags: ghcr.io/divolgin/actions-runner:${{ steps.generate-tag.outputs.tag }}
          provenance: false
